### ISSUE TITLE
Testing variable values

### ISSUE THREAD

**Issue by TxHawks** [ryanbahniuk/sassaby#20]
Is it possible to test variable values?

A use case would be to test is a mixin correctly changes a global config variable.

**Comment by ryanbahniuk** [comment]
No, we didn't build this in because all of our mixins are purely functional. On a side note, what would be the goal of changing global state of your Sass environment by calling a mixin?

**Comment by TxHawks** [comment]
Thanks for the reply.

The goal would be to have access to the variable from within `@content`, as it doesn't have access to the mixin scope
